# Generated by Django 4.1.5 on 2023-01-04 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
